name: Release

on: 
  push:
    branches: [ master ]

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet publish -c Release -r linux-x64 --no-self-contained
      - name: Zip
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -j -r latest.zip /github/workspace/SS14.Watchdog/bin/Release/net6.0/linux-x64/publish/
      - name: Release to Bucket
        uses: koraykoska/s3-upload-github-action@master
        env:
          FILE: latest.zip
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_PREFIX: 'builds'
